name: CI
on:
  push:
    branches: [main]
  pull_request:

jobs:
  test:
    strategy:
      matrix:
        optimize: [Debug, ReleaseSafe, ReleaseFast]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: mlugg/setup-zig@v1
        with:
          version: 0.13.0
      - name: Install Arm GNU Toolchain (arm-none-eabi-gcc)
        uses: carlosperate/arm-none-eabi-gcc-action@v1
        with:
          release: '13.2.Rel1'
      - name: Zig Tests
        run: zig build test -Doptimize=${{ matrix.optimize }}
      - name: Build Example
        working-directory: ./example
        run: zig build -Dtarget=thumb-freestanding-eabihf -Dcpu=cortex_m7+fp_armv8d16sp -Doptimize=${{ matrix.optimize }}
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: mlugg/setup-zig@v1
        with:
          version: 0.13.0
      - run: zig fmt --check .
